# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "2.1"

services:
  node:
    restart: always
    image: docker.io/bitnami/node:18.18.0
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
